#!/bin/bash

# Creates tarball of configuration system for updates of client installations
# To update an existing installation with this snapshot use
#   scripts/update-proj    proj-ver.tbz2  (from root directory)

# for this script to work you have to have text file 'version'
# with a version (as a string) inside 

n=`basename $PWD`-`cat version`
t=$n.tbz2
pwd=`pwd`

td=/tmp/$$
mkdir $td || exit 1
cd $td 
ln -s $pwd $n
tar hjcvf $t --exclude .svn $n
cd -
cp $td/$t ..
ls -al ../$t
rm -rf $td

